# Generated by Django 5.2.7 on 2026-01-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_profile_college_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading (e.g., Happy New Year 2026!)', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subheading (e.g., Kickstart your journey...)', max_length=200, null=True)),
                ('content', models.TextField(blank=True, help_text='Main body text, supports HTML for bolding etc.', null=True)),
                ('highlighted_text', models.CharField(blank=True, help_text='Text shown in the highlighted pill/box', max_length=200, null=True)),
                ('button_text', models.CharField(default='Show Me The Programs ⚡', max_length=50)),
                ('button_link', models.CharField(default='/training/', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Check this to show the popup to users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
