# Generated by Django 5.2.7 on 2026-01-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_college_alter_answer_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All Users'), ('VISITORS', 'Visitors/Newcomers (No Active Plan)'), ('STUDENTS', 'Active Students (Has Active Plan)')], default='ALL', help_text='Who should see this announcement?', max_length=20),
        ),
    ]
