# Generated by Django 6.0.4 on 2026-04-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('0-1 Years', '0–1 Years'), ('1-2 Years', '1–2 Years'), ('2-3 Years', '2–3 Years'), ('Above 3 Years', 'Above 3 Years')], max_length=50)),
                ('practice_instrument', models.CharField(max_length=50)),
                ('swar_identification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workshop Registration',
                'verbose_name_plural': 'Workshop Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
