# Generated by Django 6.0.4 on 2026-04-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_workshopregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(default='Md Shahbaz Khan', max_length=100)),
                ('subtitle', models.CharField(default='Your Guide & Mentor', max_length=200)),
                ('bio', models.TextField()),
                ('experience_years', models.CharField(default='15+', max_length=20)),
                ('students_trained', models.CharField(default='500+', max_length=20)),
                ('instructor_image', models.ImageField(blank=True, null=True, upload_to='landing/about/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '2. Mentor Section',
                'verbose_name_plural': '2. Mentor Sections',
            },
        ),
        migrations.CreateModel(
            name='WorkshopFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '5. FAQ',
                'verbose_name_plural': '5. FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '4. Gallery Image',
                'verbose_name_plural': '4. Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Master the Soul of Vocal Music', max_length=200)),
                ('subtitle', models.CharField(default='A Premium Clinical Riyaaz Experience', max_length=300)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('cta_primary_text', models.CharField(default='Join Free Workshop', max_length=50)),
                ('cta_secondary_text', models.CharField(default='Learn More', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '1. Hero Section',
                'verbose_name_plural': '1. Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='WorkshopProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='music', help_text='Lucide icon name (e.g., music, users, clock)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/programs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '3. Program Card',
                'verbose_name_plural': '3. Program Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='Admin internal label', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/sections/')),
                ('image_alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '6. Custom Section',
                'verbose_name_plural': '6. Custom Sections',
                'ordering': ['order'],
            },
        ),
    ]
