# Generated by Django 6.0.4 on 2026-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_workshopabout_workshopfaq_workshopgallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='If active, this content will override hardcoded template content.')),
                ('title_tag', models.CharField(default='RecgetUp Music | Classical Vocal Workshop', help_text='Browser tab title', max_length=100)),
                ('hero_badge_en', models.CharField(default='Beginner Friendly • Limited Seats', max_length=200)),
                ('hero_title_en', models.CharField(default='Refine Your Voice Through Timeless Classical Training', max_length=255)),
                ('hero_desc_en', models.TextField(default='Experience a disciplined journey of riyaaz, guided mentorship, and structured learning designed to build your musical identity.')),
                ('btn_join_workshop_en', models.CharField(default='Join Free Workshop', max_length=100)),
                ('btn_register_now_en', models.CharField(default='Register Now', max_length=100)),
                ('hero_badge_hi', models.CharField(default='शुरुआती लोगों के लिए • सीमित सीटें', max_length=200)),
                ('hero_title_hi', models.CharField(default='कालातीत शास्त्रीय प्रशिक्षण के माध्यम से अपनी आवाज़ को निखारें', max_length=255)),
                ('hero_desc_hi', models.TextField(default='रियाज़ की एक अनुशासित यात्रा, निर्देशित मेंटरशिप और अपनी संगीत पहचान बनाने के लिए डिज़ाइन की गई संरचित शिक्षा का अनुभव करें।')),
                ('btn_join_workshop_hi', models.CharField(default='फ्री वर्कशॉप ज्वाइन करें', max_length=100)),
                ('btn_register_now_hi', models.CharField(default='अभी रजिस्टर करें', max_length=100)),
                ('tag_free_en', models.CharField(default='FREE', max_length=50)),
                ('tag_free_hi', models.CharField(default='मुफ्त', max_length=50)),
                ('price_label_en', models.CharField(default='Workshop Value', max_length=100)),
                ('price_label_hi', models.CharField(default='वर्कशॉप की वैल्यू', max_length=100)),
                ('old_price', models.IntegerField(default=499)),
                ('new_price', models.IntegerField(default=0)),
                ('hero_image', models.ImageField(blank=True, help_text='Upload new hero image (png/jpg)', null=True, upload_to='landing/hero/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Configuration',
                'verbose_name_plural': 'Landing Page Configuration',
            },
        ),
        migrations.DeleteModel(
            name='WorkshopAbout',
        ),
        migrations.DeleteModel(
            name='WorkshopFAQ',
        ),
        migrations.DeleteModel(
            name='WorkshopGallery',
        ),
        migrations.DeleteModel(
            name='WorkshopHero',
        ),
        migrations.DeleteModel(
            name='WorkshopProgram',
        ),
        migrations.DeleteModel(
            name='WorkshopSection',
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
