# Generated by Django 6.0.4 on 2026-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_landingpageconfig_delete_workshopabout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='urgency_text_en',
            field=models.CharField(default='Free Workshop Starting Soon • Limited Free Seats Available • Reserve Your Spot Now', max_length=500),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='urgency_text_hi',
            field=models.CharField(default='फ्री वर्कशॉप जल्द शुरू हो रही है • सीमित सीटें उपलब्ध • अपनी सीट अभी सुरक्षित करें', max_length=500),
        ),
    ]
