# Generated by Django 6.0.4 on 2026-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_landingpageconfig_urgency_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='card1_desc_en',
            field=models.TextField(default='Master the science of breath control and pitch stability to eliminate vocal strain forever.'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card1_desc_hi',
            field=models.TextField(default='सांस पर नियंत्रण और पिच स्थिरता की विज्ञान आधारित तकनीकें सीखें और आवाज़ के तनाव को दूर करें।'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card1_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/mastery/'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card1_title_en',
            field=models.CharField(default='Precision Technique', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card1_title_hi',
            field=models.CharField(default='सटीक गायन तकनीक', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card2_desc_en',
            field=models.TextField(default='Understand the core identity of Ragas and learn to weave deep emotions into every note.'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card2_desc_hi',
            field=models.TextField(default='रागों की असली पहचान को समझें और हर सुर में गहरे भाव पिरोना सीखें।'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card2_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/mastery/'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card2_title_en',
            field=models.CharField(default='Raga Mastery & Soul', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card2_title_hi',
            field=models.CharField(default='रागों की गहराई और आत्मा', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card3_desc_en',
            field=models.TextField(default='Get a personalized step-by-step plan to transition from a student to a confident performer.'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card3_desc_hi',
            field=models.TextField(default='एक छात्र से एक आत्मविश्वासी कलाकार बनने के लिए व्यक्तिगत चरण-दर-चरण योजना प्राप्त करें।'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card3_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/mastery/'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card3_title_en',
            field=models.CharField(default="Performer's Roadmap", max_length=200),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='card3_title_hi',
            field=models.CharField(default='परफ़ॉर्मर का रोडमैप', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='mastery_desc_en',
            field=models.TextField(default='Three pillars of your scientific musical journey.'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='mastery_desc_hi',
            field=models.TextField(default='आपकी संगीतमय यात्रा के तीन मुख्य स्तंभ।'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='mastery_subtitle_en',
            field=models.CharField(default='Your Transformation', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='mastery_subtitle_hi',
            field=models.CharField(default='आपका परिवर्तन', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='mastery_title_en',
            field=models.CharField(default='What You Will Master', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='mastery_title_hi',
            field=models.CharField(default='आप क्या सीखेंगे', max_length=255),
        ),
    ]
