# Generated by Django 6.0.4 on 2026-04-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_landingpageconfig_card1_desc_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card1_desc_en',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card1_desc_hi',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card1_image',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card1_title_en',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card1_title_hi',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card2_desc_en',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card2_desc_hi',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card2_image',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card2_title_en',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card2_title_hi',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card3_desc_en',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card3_desc_hi',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card3_image',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card3_title_en',
        ),
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='card3_title_hi',
        ),
        migrations.CreateModel(
            name='LandingPageMasteryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_hi', models.CharField(max_length=200)),
                ('desc_en', models.TextField()),
                ('desc_hi', models.TextField()),
                ('image', models.ImageField(upload_to='landing/mastery/')),
                ('icon_class', models.CharField(default='lucide-mic-2', help_text='Lucide icon name (e.g. lucide-sparkles)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_cards', to='landingpage.landingpageconfig')),
            ],
            options={
                'verbose_name': 'Mastery Card',
                'verbose_name_plural': 'Mastery Cards',
                'ordering': ['order'],
            },
        ),
    ]
