# Generated by Django 6.0.4 on 2026-04-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_remove_landingpageconfig_card1_desc_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('subtitle_en', models.CharField(default='The Learning Path', max_length=200)),
                ('subtitle_hi', models.CharField(default='सीखने की राह', max_length=200)),
                ('title_en', models.CharField(default='Workshop Schedule', max_length=255)),
                ('title_hi', models.CharField(default='वर्कशॉप शेड्यूल', max_length=255)),
                ('desc_en', models.TextField(default='A scientifically structured journey into the depths of Hindustani Classical Vocal.')),
                ('desc_hi', models.TextField(default='हिंदुस्तानी शास्त्रीय गायन की गहराइयों में एक वैज्ञानिक रूप से संरचित यात्रा।')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Only one Hero section can be active at a time.')),
                ('title_tag', models.CharField(default='RecgetUp Music | Vocal Excellence', help_text='Browser tab title', max_length=255)),
                ('badge_en', models.CharField(default='PREMIUM CLASSICAL ACADEMY', max_length=100)),
                ('title_en', models.CharField(default='Master the Soul of Hindustani Classical Vocal', max_length=255)),
                ('desc_en', models.TextField(default='A scientifically designed journey from basic swars to advanced Raga mastery. Join our exclusive workshop to transform your vocal technique.')),
                ('btn_join_en', models.CharField(default='Join Free Workshop', max_length=100)),
                ('btn_register_en', models.CharField(default='Register Now', max_length=100)),
                ('badge_hi', models.CharField(default='प्रीमियम शास्त्रीय अकादमी', max_length=100)),
                ('title_hi', models.CharField(default='हिंदुस्तानी शास्त्रीय गायन की आत्मा में महारत हासिल करें', max_length=255)),
                ('desc_hi', models.TextField(default='बुनियादी स्वरों से लेकर उन्नत राग महारत तक की एक वैज्ञानिक रूप से तैयार की गई यात्रा। अपनी गायन तकनीक को बदलने के लिए हमारी विशेष वर्कशॉप में शामिल हों।')),
                ('btn_join_hi', models.CharField(default='फ्री वर्कशॉप ज्वाइन करें', max_length=100)),
                ('btn_register_hi', models.CharField(default='अभी रजिस्टर करें', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
            ],
        ),
        migrations.CreateModel(
            name='MarqueeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('text_en', models.CharField(default='Free Workshop Starting Soon • Limited Free Seats Available • Reserve Your Spot Now', max_length=500)),
                ('text_hi', models.CharField(default='फ्री वर्कशॉप जल्द शुरू हो रही है • सीमित सीटें उपलब्ध • अपनी सीट अभी सुरक्षित करें', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MasterySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('subtitle_en', models.CharField(default='Your Transformation', max_length=200)),
                ('subtitle_hi', models.CharField(default='आपका परिवर्तन', max_length=200)),
                ('title_en', models.CharField(default='What You Will Master', max_length=255)),
                ('title_hi', models.CharField(default='आप क्या सीखेंगे', max_length=255)),
                ('desc_en', models.TextField(default='Three pillars of your scientific musical journey.')),
                ('desc_hi', models.TextField(default='आपकी संगीतमय यात्रा के तीन मुख्य स्तंभ।')),
            ],
        ),
        migrations.CreateModel(
            name='MentorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('subtitle_en', models.CharField(default='Your Guide & Mentor', max_length=200)),
                ('subtitle_hi', models.CharField(default='आपके मार्गदर्शक और मेंटर', max_length=200)),
                ('name_en', models.CharField(default='Md Shahbaz Khan', max_length=255)),
                ('name_hi', models.CharField(default='MD SHAHBAZ KHAN', max_length=255)),
                ('tagline_en', models.CharField(default='Classical Vocal Mentor', max_length=255)),
                ('tagline_hi', models.CharField(default='शास्त्रीय गायन शिक्षक', max_length=255)),
                ('quote_en', models.TextField(default='“True classical training is about discipline, patience, and discovering the depth of your own voice.”')),
                ('quote_hi', models.TextField(default='“सच्चा शास्त्रीय प्रशिक्षण अनुशासन, धैर्य और अपनी आवाज़ की गहराई को खोजने के बारे में है।”')),
                ('bio_en', models.TextField(default='With years of dedicated training in Hindustani Classical music, Md Shahbaz Khan has mentored students across all levels.')),
                ('bio_hi', models.TextField(default='हिंदुस्तानी शास्त्रीय संगीत में वर्षों के समर्पित प्रशिक्षण के साथ, एमडी शाहबाज़ खान ने सभी स्तरों के छात्रों को प्रशिक्षित किया है।')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/mentor/')),
                ('exp_num', models.CharField(default='15+', max_length=50)),
                ('exp_label_en', models.CharField(default='Years Experience', max_length=100)),
                ('exp_label_hi', models.CharField(default='वर्षों का अनुभव', max_length=100)),
                ('students_num', models.CharField(default='500+', max_length=50)),
                ('students_label_en', models.CharField(default='Vocalists Trained', max_length=100)),
                ('students_label_hi', models.CharField(default='छात्र प्रशिक्षित', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('label_en', models.CharField(default='Workshop Value', max_length=100)),
                ('label_hi', models.CharField(default='वर्कशॉप की वैल्यू', max_length=100)),
                ('old_price', models.IntegerField(default=499)),
                ('new_price', models.IntegerField(default=0)),
                ('tag_free_en', models.CharField(default='FREE', max_length=50)),
                ('tag_free_hi', models.CharField(default='मुफ्त', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title_en', models.CharField(default='Seats Filling Fast for Free Session', max_length=255)),
                ('title_hi', models.CharField(default='फ्री सेशन के लिए सीटें तेज़ी से भर रही हैं', max_length=255)),
                ('desc_en', models.TextField(default='Limited free seats available for the upcoming session. Secure your spot before enrollment closes.')),
                ('desc_hi', models.TextField(default='आने वाले सेशन के लिए सीमित मुफ़्त सीटें। नामांकन बंद होने से पहले अपना स्थान सुरक्षित करें।')),
                ('btn_text_en', models.CharField(default='Reserve My Seat', max_length=100)),
                ('btn_text_hi', models.CharField(default='अपनी सीट सुरक्षित करें', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='landingpagemasterycard',
            name='config',
        ),
        migrations.AlterModelOptions(
            name='vocalworkshopquery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workshopregistration',
            options={},
        ),
        migrations.RenameField(
            model_name='vocalworkshopquery',
            old_name='question',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='vocalworkshopquery',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='workshopregistration',
            name='age',
        ),
        migrations.RemoveField(
            model_name='workshopregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workshopregistration',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='workshopregistration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workshopregistration',
            name='practice_instrument',
        ),
        migrations.RemoveField(
            model_name='workshopregistration',
            name='state',
        ),
        migrations.RemoveField(
            model_name='workshopregistration',
            name='swar_identification',
        ),
        migrations.AddField(
            model_name='vocalworkshopquery',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='experience',
            field=models.CharField(choices=[('0-1 Years', '0–1 Years'), ('1-3 Years', '1–3 Years'), ('3-5 Years', '3–5 Years'), ('5+ Years', '5+ Years')], default='0-1 Years', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocalworkshopquery',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='CurriculumStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_hi', models.CharField(max_length=200)),
                ('desc_en', models.TextField()),
                ('desc_hi', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='landingpage.curriculumsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MasteryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_hi', models.CharField(max_length=200)),
                ('desc_en', models.TextField()),
                ('desc_hi', models.TextField()),
                ('image', models.ImageField(upload_to='landing/mastery/')),
                ('icon_class', models.CharField(default='lucide-mic-2', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='landingpage.masterysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='LandingPageConfig',
        ),
        migrations.DeleteModel(
            name='LandingPageMasteryCard',
        ),
    ]
