# Generated by Django 6.0.4 on 2026-04-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_curriculumsection_herosection_marqueesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title_en', models.CharField(default='Frequently Asked Questions', max_length=200)),
                ('title_hi', models.CharField(default='अक्सर पूछे जाने वाले प्रश्न', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title_en', models.CharField(default='Inside the Academy', max_length=200)),
                ('title_hi', models.CharField(default='अकादमी के अंदर', max_length=200)),
                ('desc_en', models.TextField(default='A glimpse into our soulful musical environment.')),
                ('desc_hi', models.TextField(default='हमारे संगीतमय वातावरण की एक झलक।')),
            ],
        ),
        migrations.AddField(
            model_name='timersection',
            name='target_date',
            field=models.DateTimeField(blank=True, help_text='The date and time the countdown ends.', null=True),
        ),
        migrations.AlterField(
            model_name='timersection',
            name='desc_hi',
            field=models.TextField(default='आने वाले सेशन के लिए सीमित मुफ़्त सीटें। नामांकन बंद होने से पहले अपना स्थान सुरक्षित करें।'),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=500)),
                ('question_hi', models.CharField(max_length=500)),
                ('answer_en', models.TextField()),
                ('answer_hi', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='landingpage.faqsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False, help_text='Show this as the large feature image.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landingpage.gallerysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
