# Generated by Django 6.0.4 on 2026-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_faqsection_gallerysection_timersection_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocalworkshopquery',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
