# Generated by Django 6.0.4 on 2026-04-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_vocalworkshopquery_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopregistration',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='instrument',
            field=models.CharField(choices=[('Harmonium', 'Harmonium'), ('Tanpura', 'Tanpura')], default='0000000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='swar_identification',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='experience',
            field=models.CharField(choices=[('0-1', '0–1 Years'), ('1-2', '1–2 Years'), ('2-3', '2–3 Years'), ('Above 3', 'Above 3 Years')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='whatsapp_number',
            field=models.CharField(default='0-1', max_length=15),
            preserve_default=False,
        ),
    ]
