# Generated by Django 6.0.4 on 2026-04-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_remove_workshopregistration_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/curriculum/'),
        ),
    ]
