# Generated by Django 6.0.4 on 2026-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_curriculumstep_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('whatsapp_link', models.URLField(default='https://chat.whatsapp.com/JqEzO72JNggAi6fErSWrxX')),
                ('contact_email', models.EmailField(default='info@recgetup.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91 00000 00000', max_length=20)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(default='© 2026 RECGETUP MUSIC. CRAFTED FOR MUSICAL EXCELLENCE.', max_length=255)),
            ],
        ),
    ]
