# Generated by Django 6.0.4 on 2026-04-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/curriculum/bg/'),
        ),
        migrations.AddField(
            model_name='gallerysection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/gallery/bg/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background Image for Hero', null=True, upload_to='landing/hero/bg/'),
        ),
        migrations.AddField(
            model_name='masterysection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/mastery/bg/'),
        ),
        migrations.AddField(
            model_name='mentorsection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/mentor/bg/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='body_background',
            field=models.ImageField(blank=True, null=True, upload_to='landing/site/bg/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_background',
            field=models.ImageField(blank=True, null=True, upload_to='landing/site/footer/'),
        ),
        migrations.AddField(
            model_name='timersection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/timer/bg/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, help_text='Main Hero Image (Foreground)', null=True, upload_to='landing/hero/'),
        ),
    ]
