# Generated by Django 6.0.4 on 2026-05-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0014_curriculumsection_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video (MP4/WebM) to turn this item into a video preview.', null=True, upload_to='landing/gallery/videos/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Image or Video Thumbnail', upload_to='landing/gallery/'),
        ),
    ]
