# Generated by Django 6.0.4 on 2026-05-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_galleryimage_video_alter_galleryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='video',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='media_file',
            field=models.FileField(default='', help_text='Upload an Image or Video file.', upload_to='landing/gallery/'),
            preserve_default=False,
        ),
    ]
