# Generated by Django 5.2.7 on 2025-12-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_attempt_lifelines_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Quiz closes at this time.', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Quiz becomes accessible at this time.', null=True),
        ),
    ]
