# Generated by Django 5.2.7 on 2025-12-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_quiz_end_time_quiz_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='generate_certificate',
            field=models.BooleanField(default=True, help_text='If checked, students can download a certificate after passing.'),
        ),
    ]
