# Generated by Django 5.2.7 on 2025-12-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_quiz_generate_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonResult',
            fields=[
            ],
            options={
                'verbose_name': 'Hackathon Result',
                'verbose_name_plural': 'Hackathon Results',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quizzes.quiz',),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
