# Generated by Django 5.2.7 on 2026-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='next_payment_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='includes_special_access',
            field=models.BooleanField(default=False, help_text='Check to grant Special Class access to this student/coupon'),
        ),
    ]
