# Generated by Django 5.2.7 on 2026-01-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_coupon_next_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoppackage',
            name='includes_special_access',
        ),
    ]
