# Generated by Django 5.2.7 on 2026-01-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_workshop_options_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Training Program', 'verbose_name_plural': 'Training Programs'},
        ),
    ]
