# Generated by Django 5.2.7 on 2026-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_workshoppackage_includes_special_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='Check if this batch is for 1-on-1 Personal Classes'),
        ),
    ]
