# Generated by Django 5.2.7 on 2026-01-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_workshop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='reminder_30min_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='reminder_6hr_sent',
            field=models.BooleanField(default=False),
        ),
    ]
