# Generated by Django 5.2.7 on 2026-01-16 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_classschedule_reminder_30min_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='Assigned Tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
