# Generated by Django 5.2.7 on 2026-01-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_batch_is_personal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Student Attendance'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches (Groups & Personal)'},
        ),
        migrations.AlterModelOptions(
            name='classsession',
            options={'verbose_name': 'Reschedule / Extra Class', 'verbose_name_plural': 'Reschedule / Extra Classes'},
        ),
        migrations.AlterModelOptions(
            name='contactquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Website Inquiry', 'verbose_name_plural': 'Website Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Coupon / Assign Student', 'verbose_name_plural': 'Coupons / Assign Student'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name_plural': 'Active Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Class Resource', 'verbose_name_plural': 'Class Resources'},
        ),
        migrations.AlterModelOptions(
            name='specialclass',
            options={'verbose_name_plural': 'Special Classes'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Program / Subject', 'verbose_name_plural': 'Programs / Subjects'},
        ),
        migrations.AlterModelOptions(
            name='workshoppackage',
            options={'verbose_name': 'Pricing Package', 'verbose_name_plural': 'Pricing Packages'},
        ),
    ]
