# Generated by Django 5.2.7 on 2026-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_attendance_options_alter_batch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='enrollment_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='enrollment_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_days',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Duration in days', null=True),
        ),
    ]
