# Generated by Django 5.2.7 on 2026-01-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='expiry_1d_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='expiry_3d_sent',
            field=models.BooleanField(default=False),
        ),
    ]
