# Generated by Django 5.2.7 on 2026-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_enrollment_expiry_1d_sent_enrollment_expiry_3d_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialclass',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Required for Recurring events', null=True),
        ),
        migrations.AddField(
            model_name='specialclass',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Required for Recurring events', null=True),
        ),
        migrations.AddField(
            model_name='specialclass',
            name='scheduling_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring (Weekly)')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='specialclass',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Required for Recurring events', null=True),
        ),
        migrations.AlterField(
            model_name='specialclass',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Required for One Time events', null=True),
        ),
        migrations.AlterField(
            model_name='specialclass',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Required for One Time events', null=True),
        ),
    ]
