# Generated by Django 5.2.7 on 2026-02-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_specialclass_day_of_week_specialclass_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='recording_link',
            field=models.URLField(blank=True, help_text='Link to the class recording (e.g. Zoom cloud/Drive)', max_length=500, null=True),
        ),
    ]
