# Generated by Django 6.0.4 on 2026-04-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_classsession_recording_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='recording_link',
        ),
    ]
