# Generated by Django 6.0.4 on 2026-04-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_remove_classsession_recording_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'About Section'},
        ),
        migrations.AlterModelOptions(
            name='classtype',
            options={'ordering': ['order'], 'verbose_name': 'Class Type'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Gallery Image'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Section'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial'},
        ),
    ]
