# Generated by Django 6.0.4 on 2026-04-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_landingpagesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageSection',
        ),
    ]
